// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/blogs/:blogHandle/:articleHandle": {
    params: {
      "blogHandle": string;
      "articleHandle": string;
    };
  };
  "/sitemap/:type/:page.xml": {
    params: {
      "type": string;
      "page": string;
    };
  };
  "/blogs/:blogHandle": {
    params: {
      "blogHandle": string;
    };
  };
  "/collections/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/authorize": {
    params: {};
  };
  "/collections": {
    params: {};
  };
  "/policies/:handle": {
    params: {
      "handle": string;
    };
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/account/logout": {
    params: {};
  };
  "/collections/all": {
    params: {};
  };
  "/policies": {
    params: {};
  };
  "/account/login": {
    params: {};
  };
  "/discount/:code": {
    params: {
      "code": string;
    };
  };
  "/sitemap.xml": {
    params: {};
  };
  "/pages/:handle": {
    params: {
      "handle": string;
    };
  };
  "/robots.txt": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/orders": {
    params: {};
  };
  "/account/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/account/addresses": {
    params: {};
  };
  "/account/profile": {
    params: {};
  };
  "/account/*": {
    params: {
      "*": string;
    };
  };
  "/search": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/cart/:lines": {
    params: {
      "lines": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/blogs/:blogHandle/:articleHandle" | "/sitemap/:type/:page.xml" | "/blogs/:blogHandle" | "/collections/:handle" | "/account/authorize" | "/collections" | "/policies/:handle" | "/products/:handle" | "/account/logout" | "/collections/all" | "/policies" | "/account/login" | "/discount/:code" | "/sitemap.xml" | "/pages/:handle" | "/robots.txt" | "/blogs" | "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*" | "/search" | "/cart" | "/cart/:lines" | "/*" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/blogs.$blogHandle.$articleHandle.jsx": {
    id: "routes/blogs.$blogHandle.$articleHandle";
    page: "/blogs/:blogHandle/:articleHandle";
  };
  "routes/sitemap.$type.$page[.xml].jsx": {
    id: "routes/sitemap.$type.$page[.xml]";
    page: "/sitemap/:type/:page.xml";
  };
  "routes/blogs.$blogHandle._index.jsx": {
    id: "routes/blogs.$blogHandle._index";
    page: "/blogs/:blogHandle";
  };
  "routes/collections.$handle.jsx": {
    id: "routes/collections.$handle";
    page: "/collections/:handle";
  };
  "routes/account_.authorize.jsx": {
    id: "routes/account_.authorize";
    page: "/account/authorize";
  };
  "routes/collections._index.jsx": {
    id: "routes/collections._index";
    page: "/collections";
  };
  "routes/policies.$handle.jsx": {
    id: "routes/policies.$handle";
    page: "/policies/:handle";
  };
  "routes/products.$handle.jsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/account_.logout.jsx": {
    id: "routes/account_.logout";
    page: "/account/logout";
  };
  "routes/collections.all.jsx": {
    id: "routes/collections.all";
    page: "/collections/all";
  };
  "routes/policies._index.jsx": {
    id: "routes/policies._index";
    page: "/policies";
  };
  "routes/account_.login.jsx": {
    id: "routes/account_.login";
    page: "/account/login";
  };
  "routes/discount.$code.jsx": {
    id: "routes/discount.$code";
    page: "/discount/:code";
  };
  "routes/[sitemap.xml].jsx": {
    id: "routes/[sitemap.xml]";
    page: "/sitemap.xml";
  };
  "routes/pages.$handle.jsx": {
    id: "routes/pages.$handle";
    page: "/pages/:handle";
  };
  "routes/[robots.txt].jsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/blogs._index.jsx": {
    id: "routes/blogs._index";
    page: "/blogs";
  };
  "routes/account.jsx": {
    id: "routes/account";
    page: "/account" | "/account/orders" | "/account/orders/:id" | "/account/addresses" | "/account/profile" | "/account/*";
  };
  "routes/account.orders._index.jsx": {
    id: "routes/account.orders._index";
    page: "/account/orders";
  };
  "routes/account.orders.$id.jsx": {
    id: "routes/account.orders.$id";
    page: "/account/orders/:id";
  };
  "routes/account.addresses.jsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/account.profile.jsx": {
    id: "routes/account.profile";
    page: "/account/profile";
  };
  "routes/account._index.jsx": {
    id: "routes/account._index";
    page: "/account";
  };
  "routes/account.$.jsx": {
    id: "routes/account.$";
    page: "/account/*";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/search.jsx": {
    id: "routes/search";
    page: "/search";
  };
  "routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart" | "/cart/:lines";
  };
  "routes/cart.$lines.jsx": {
    id: "routes/cart.$lines";
    page: "/cart/:lines";
  };
  "routes/$.jsx": {
    id: "routes/$";
    page: "/*";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/todd/Documents/orgs/SWS/repos/sws-storefront/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/blogs.$blogHandle.$articleHandle": typeof import("./app/routes/blogs.$blogHandle.$articleHandle.jsx");
  "routes/sitemap.$type.$page[.xml]": typeof import("./app/routes/sitemap.$type.$page[.xml].jsx");
  "routes/blogs.$blogHandle._index": typeof import("./app/routes/blogs.$blogHandle._index.jsx");
  "routes/collections.$handle": typeof import("./app/routes/collections.$handle.jsx");
  "routes/account_.authorize": typeof import("./app/routes/account_.authorize.jsx");
  "routes/collections._index": typeof import("./app/routes/collections._index.jsx");
  "routes/policies.$handle": typeof import("./app/routes/policies.$handle.jsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.jsx");
  "routes/account_.logout": typeof import("./app/routes/account_.logout.jsx");
  "routes/collections.all": typeof import("./app/routes/collections.all.jsx");
  "routes/policies._index": typeof import("./app/routes/policies._index.jsx");
  "routes/account_.login": typeof import("./app/routes/account_.login.jsx");
  "routes/discount.$code": typeof import("./app/routes/discount.$code.jsx");
  "routes/[sitemap.xml]": typeof import("./app/routes/[sitemap.xml].jsx");
  "routes/pages.$handle": typeof import("./app/routes/pages.$handle.jsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].jsx");
  "routes/blogs._index": typeof import("./app/routes/blogs._index.jsx");
  "routes/account": typeof import("./app/routes/account.jsx");
  "routes/account.orders._index": typeof import("./app/routes/account.orders._index.jsx");
  "routes/account.orders.$id": typeof import("./app/routes/account.orders.$id.jsx");
  "routes/account.addresses": typeof import("./app/routes/account.addresses.jsx");
  "routes/account.profile": typeof import("./app/routes/account.profile.jsx");
  "routes/account._index": typeof import("./app/routes/account._index.jsx");
  "routes/account.$": typeof import("./app/routes/account.$.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/search": typeof import("./app/routes/search.jsx");
  "routes/cart": typeof import("./app/routes/cart.jsx");
  "routes/cart.$lines": typeof import("./app/routes/cart.$lines.jsx");
  "routes/$": typeof import("./app/routes/$.jsx");
  "/Users/todd/Documents/orgs/SWS/repos/sws-storefront/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};